name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        stable: false
        go-version: 1.18.0-beta1

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Coverage
      run: |
        go test -coverprofile=coverage.out -covermode=count  ./...
        coverage=$(go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+')
        if (( $(echo "$coverage <= 50" | bc -l) )) ; then
            color=red
          elif (( $(echo "$coverage > 80" | bc -l) )); then
            color=green
          else
            color=orange
          fi
        echo "COVERAGE=$coverage" >> $GITHUB_ENV
        echo "COLOR=$color" >> $GITHUB_ENV

    - name: Create the Badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST }}
        gistID: f78532b2b7fa732b9884ebbf0c8c23aa
        filename: gola.cov
        label: Coverage
        message: ${{ env.COVERAGE }}%
        color: ${{ env.COLOR }}

    - name: Install go report card
      run: |
        git clone https://github.com/gojp/goreportcard.git
        cd goreportcard
        make install
        go get -u github.com/client9/misspell/cmd/misspell
        go install ./cmd/goreportcard-cli
      
    - name: Run go report card
      run: goreportcard-cli