# This workflow add GitHub issues to Project and label them for triage upon creation

name: WeCom test
on:
  issues:
    types:
      - opened
      - reopened

jobs:
  notify_wecom:
    name: send bug notification to wecom
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.issue.labels.*.name, 'bug') }}
    steps:
      - name: Clean up body message
        run: |
          content=$(cat<<EOF | jq -Rs '.'
          # <font color=\"warning\">${{ github.event.issue.title }}</font>
          $(echo '${{ github.event.issue.body }}' | sed -e '/<!--/d' | sed -e 's/ ###//g')

          [查看原文](${{ github.event.issue.html_url }})
          EOF
          )
          echo "MSG_CONTENT='$content'"> $GITHUB_ENV

      - name: Send to WeCom
        run: |
          curl -s '${{ secrets.BOT_URL }}' \
          -H 'Content-Type: application/json' \
          -d '
          {
              "msgtype": "markdown",
              "markdown": {
                  "content": "${{ env.MSG_CONTENT }}"
              }
          }';
