# This workflow add GitHub issues to Project and label them for triage upon creation

name: WeCom test
on:
  issues:
    types:
      - opened
      - reopened

jobs:
  notify_wecom:
    name: send bug notification to wecom
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.issue.labels.*.name, 'bug') }}
    steps:
      - name: Clean up body message
        run: |
          content=$(echo '${{ github.event.issue.body }}' | sed -e 's/<!--[^>]*-->[\r\n]*//g' | sed -e 's/ ###//g')
          curl -s '${{ secrets.BOT_URL }}' \
          -H 'Content-Type: application/json' \
          -d "
          {
              "msgtype": "markdown",
              "markdown": {
                  "content": "# <font color=\"warning\">${{ github.event.issue.title }}</font>\r\n\r\n${content}\r\n[查看原文](${{ github.event.issue.html_url }})"
              }
          }";
